######################################################################
#
# PROJECT EULER PROBLEM 2
#
# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms will
# be 1,2,3,5,8,13,21,34,55,89,...
#
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million,find the sum of the even valued terms
#
#
# EXPLANATION OF SOLUTION
#
# Looking at the fibonacci sequence, eg. 1 2 3 5 8 13 21 34 55 89,
# You would realise that  2 is the first even number.
# Now,when you start counting from 3 onwards,you would see that
# every third number is an even number.
# Now,if we have 3 variables x,y,z that are alternating starting from 3
# and based on the rules of generating fibonnaci numbers,
# you would realise that the value of z is always the value of the next
# even number in the series
#
# This observation is not any magic at all.We know that the sum of two
# odd numbers is an even number.The sum of an odd number and an even
# number is an odd number.From this fact,you can see why the value of z
# is always even since x and y are always odd
#
# So to sum up even numbers,we just keep summing the values of z
#
########################################################################

sumEven = 0

x = 1
y = 1
z = 2

while z <= 4000000:
    sumEven += z    # 2 is the first even number

    # moving x,y and z to their next values based on
    # the definition of fibonacci numbers
    x = y + z       
    y = z + x
    z = x + y

print sumEven
